version: "3"
services:
  haproxy:
    image: haproxy:1.7
    volumes:
      - ./:/usr/local/etc/haproxy:ro
    ports:
      - "5000:80"
    links:
      - square-service

  square-service:
    image: learncloudnative/square:0.1.0
